[package]
name = "rsimg"
version = "0.1.0"
edition = "2024"
rust-version = "1.86"

[dependencies]
crossterm = "0.27" 
zune-jpeg = "0.5.12"
zune-core = "0.5.1"

[profile.dev.package.zune-jpeg]
opt-level = 3
